project:
  type: website
  output-dir: _site

website:
  title: "Apuntes: Administración de Bases de Datos"
  description: "Mi repositorio personal de apuntes del curso."
  # Barra de navegación superior
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Inicio

  # Barra lateral izquierda (Organizada por bloques del curso)
  sidebar:
#   style: "docked"
    style: "floating" # Entire sidebar hides/shows with a toggle button
    search: true
#    collapse-level: 1 # This makes sections collapsible!
    contents:
      - section: "Bloque 1: Redes e Infraestructura"
        contents:
          - href: intro.qmd
            text: "Tema 1: Redes y Protocolos"
          - href: Ordenadores.qmd
            text: "Tema 2: Conceptos de ordenadores  y servidores"      

      # Ejemplo de cómo añadir el siguiente bloque cuando lo veas en clase:
      # - section: "Bloque 2: Introducción a SQL"
      #   contents:
      #     - href: tema2_sql.qmd
      #       text: "Tema 2: Primeras Consultas"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "En este tema"
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-copy: true

editor: visual