project:
  type: website
  output-dir: _site

website:
  title: "Apuntes: Administración de Bases de Datos"
  description: "Mi repositorio personal de apuntes del curso."
  # Barra de navegación superior
  navbar:
    background: primary
    search: true
    left:
      - href: index.html
        text: Inicio

  # Barra lateral izquierda (Organizada por bloques del curso)
  sidebar:
#   style: "docked"
    style: "floating" # Entire sidebar hides/shows with a toggle button
    search: true
#    collapse-level: 1 # This makes sections collapsible!
    contents:
      - section: "Bloque 1: Redes e Infraestructura"
        contents:
          - href: intro.html
            text: "Tema 1: Redes y Protocolos"
          - href: ordenadores.html
            text: "Tema 2: Conceptos de ordenadores  y servidores"      
          - href: sistemas_operativos.html
            text: "Tema 3: Sistemas Operativos"    
          - href: virtualizacion.html
            text: "Tema 4: Virtualizacion"      
      - section: "Anexos"
        contents:
           - href: ubuntu_cheat_sheet.html
             text: "Ubunto Cheat Sheet"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "En este tema"
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-copy: true

editor: visual
