project:
  type: website
  output-dir: _site
execute:
  freeze: auto  # Congela el código y los resultados de las celdas para que no se vuelvan a ejecutar automáticamente al renderizar el sitio web.

website:
  title: "Apuntes: Administración de Bases de Datos"
  description: "Mi repositorio personal de apuntes del curso."
  google-analytics: "G-9341LNVJM3" 
  
  # Barra de navegación superior
  navbar:
    background: primary
    search: true
    left:
      - href: index.html
        text: Inicio

  # Barra lateral izquierda (Organizada por bloques del curso)
  sidebar:
    style: "floating" # La barra lateral entera se oculta/muestra con un botón flotante
    search: true
    collapse-level: 2 # Permite que los submenús se puedan colapsar/desplegar limpiamente
    contents:
      - section: "Bloque 1: Redes e Infraestructura"
        contents:
          - href: intro.html
            text: "Redes y Protocolos"
          - href: proxy.html
            text: "Servidores Proxy"
          - href: ordenadores.html
            text: "Conceptos de ordenadores y servidores"      
          - href: sistemas_operativos.html
            text: "Sistemas Operativos"    
          - section: "Virtualizacion"
            contents:
              - href: virtualizacion.html
                text: "Virtualizacion"      
              - href: laboratorio_virtualizacion.html
                text: "Guía de Pruebas de Conectividad en Entornos de Virtualización"   
              - href: servidor_linux_intro.html
                text: "Manejando un servidor Linux"   
              - href: ejercicio_linux.html
                text: "Práctica: manejando un servidor Linux"    
              - href: ubuntu_ssh.html
                text: "Guía: Configuración de SSH en Ubuntu"  
              - href: contenedores.html
                text: "Contenedores"
          - section: "Procesos, Servicios, Tareas y Procesos en Segundo Plano"
            contents:
              - href: procesos.html
                text: "Procesos, Servicios, Tareas y Procesos en Segundo Plano"               
              - section: "Monitorización de Sistemas"
                contents:    
                  - href: windows_monitoring.html
                    text: "Monitorización de Sistemas Windows"
                  - href: system_monitor_grafana.html
                    text: "Extra: crear un monitor sencillo con grafana en Windows"    
                  - href: linux_monitoring.html
                    text: "Monitorización de Sistemas Linux"
                  - href: monitor_Grafana_Ubuntu.html
                    text: "Crear un monitor sencillo con Grafana en Ubuntu Sever"
                  - href: practica_monitorizacion_completa.html
                    text: "Monitorización de tres máquinas virtuales mediante Prometheus y Grafana"
      
      - section: "Bloque 2: Bases de Datos"
        contents:
          - href: datos.html
            text: "Introducción a los datos y bases de datos"
          - href: ejercicio_modelado_datos.html
            text: "Ejercicio: Modelado de Datos"
                  
      - section: "Anexos"
        contents:
          - href: ubuntu_cheat_sheet.html
            text: "Ubuntu Cheat Sheet"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "En este tema"
    toc-depth: 4
    number-sections: true
    code-fold: false
    code-copy: true

editor: visual