name: Deploy Quarto site to Pages

on:
  push:
    branches: ["master"] # Triggers every time you push to master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # 1. Instalamos Quarto en el servidor de GitHub
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      # 2. Le decimos a Quarto que construya la web (esto genera la carpeta _site actualizada)
      - name: Render Quarto Project
        run: quarto render
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Coge la carpeta _site que Quarto acaba de generar en el paso anterior
          path: '_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
